name: CI

on:
  push:
    branches: [ "master" ]

env:
  full_name: "cao hai nhi"

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      age: 27
    steps:
      - if: ${{ env.full_name == 'cao hai nhi' }}
        run: |
          echo My name is $full_name

  job2:
    runs-on: ubuntu-latest
    env:
      favorite_dish: "spring rolls"
    steps:
      - run: |
          echo "The name was changed to $full_name"
