name: CI

on:
  push:
    branches: [ "master" ]

env:
  name: "nhi"

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      age: 27
    steps:
      - run: |
          echo My name is $name
          echo "::set-output name=name::thien"
        id: change-name

  job2:
    runs-on: ubuntu-latest
    env:
      favorite_dish: "spring rolls"
    steps:
      - run: |
          echo "The name was changed to ${{ steps.change-name.outputs.name }}"
