name: CI

on:
  push:
    branches: [ "master" ]

env:
  name: "nhi"

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      age: 27
    steps:
      - run: |
          echo My name is $name
          echo "::set-env name=name::thien"

  job2:
    runs-on: ubuntu-latest
    env:
      favorite_dish: "spring rolls"
    steps:
      - run: |
          echo $age
          echo $name
