name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # workflow_dispatch:
env:
  name: "nhi"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo $name

      - name: Run a multi-line script
        run: |
          echo $name
